# Site Settings
baseurl: ""
url : "https://zhejing-chin.github.io"

# Blog Settings
theme_settings :
  title : Jing
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/me.jpg
    username : Zhejing-Chin
    description : creator of Grape-Theme! Grape-Theme is my first jekyll theme and you can customize this theme easily.
    experience :
      - start : 2021-03-21
        end : 2022-07-23
        experience : Axrail, Data Engineer
    skills : 
      - skill : Python
        value : 75  # Percent value
        
  # Icons
  icons :
    email:  zhejingchin@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  https://www.linkedin.com/in/zhe-jing-chin/ # Full URL 
    github: Zhejing-Chin
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: aaaaahhjing

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
