# Site Settings
baseurl: ""
url : "https://zhejing-chin.github.io"

# Blog Settings
theme_settings :
  title : Jing
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/me-hague-cropped.jpg
    username : Zhejing-Chin
    description : Hi, I am Vigee. A data wizard with a dash of travel, movie, guitar, and volleyball flair!
    experience :
      - start : 2023-03-01
        end : 2023-06-01
        experience : Upwork / Fiverr, Freelance Data Engineer
      - start : 2021-03-21
        end : 2022-07-23
        experience : Axrail, Data Engineer
    skills : 
      - skill : Python
        value : 75  # Percent value
      - skill : SQL
        value : 85
      - skill : AWS Lambda
        value : 60
      - skill : PySpark
        value : 70
      - skill : Machine Learning
        value : 60
        
  # Icons
  icons :
    email:  zhejingchin@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  https://www.linkedin.com/in/zhe-jing-chin/ # Full URL 
    github: Zhejing-Chin
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: aaaaahhjing

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
