# Site Settings
baseurl: ""
url : "https://zhejing-chin.github.io"

# Blog Settings
theme_settings :
  title : Jing
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/me-hague-cropped.jpg
    username : Vigee Chin
    description : Hi, I am Vigee. A data wizard with a dash of travel, movie, guitar, and volleyball flair!   ✈️🍿🎸🏐✨
    experience :
      - start : 2023-03-01
        end : 2023-06-01
        experience : Upwork / Fiverr, Freelance Data Engineer
      - start : 2021-03-21
        end : 2022-07-23
        experience : Axrail, Data Engineer
      - start : 2020-04-01
        end : 2020-06-01
        experience : Texas Instruments, IT intern
      - start : 2019-10-01
        end : 2020-02-28
        experience : Multimedia Universty, Research Assistant
    certificates: 
      - start : May 22, 2021
        end : May 22, 2024
        title : AWS Certified Machine Learning - Specialty
    skills : 
      - skill : Python
        value : 75  # Percent value
      - skill : SQL
        value : 85
      - skill : PySpark
        value : 70
      - skill : Machine Learning
        value : 60
      - skill : AWS Lambda + SQS
        value : 70
      - skill : AWS SES
        value : 70
      - skill : AWS Glue
        value : 75
      - skill : AWS Athena
        value : 70
      - skill : Amazon Redshift
        value : 60
      - skill : AWS DMS
        value : 60
      - skill : AWS CodeCommit + CodePipeline
        value : 60
      - skill : AWS Quicksight / Tableau
        value : 80
      - skill : PowerBI
        value : 60
        
  # Icons
  icons :
    email:  zhejingchin@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  https://www.linkedin.com/in/zhe-jing-chin/ # Full URL 
    github: Zhejing-Chin
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: aaaaahhjing

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
